import React from 'react'

const Privacy = () => {
  return (
   <section className='bg-blue-100 py-10'>
         <div className="px-10 py-10 shadow-2xl rounded-lg bg-white md:mx-40">
            <h3 className='text-3xl text-center font-semibold'>Privacy Policy - Countryroof</h3>
            <p className='text-gray-600 text-base py-10'>We understand the importance of protecting the personal information you provide at Websites owned or controlled by “INFOBIRTH INNOVATIONS”
CountryRoof is an online listing portal dedicated to the Real estate industry and is owned by InfoBirth Innovations. The “privacy policies" and "terms of use” remains the same for any of the products and services owned by InfoBirth Innovations.
We take the individuals' privacy interests very seriously, whose information we receive throughout our services. We provide this Privacy Policy to describe how we use and maintain the information collected through our services and what benefits users have to control how their information is used and shared.
Please read this Privacy Policy and our Terms & Conditions carefully before using our Services. By using CountryRoof’s services, you agree to the provisions of this Privacy Policy.</p>
         <h3 className='text-2xl font-semibold'>Interpretation and Definitions</h3>
         <hr className='opacity-50 mt-2' />
         <h3 className='text-3xl font-semibold mt-5'>Interpretation</h3>
         <p className='text-gray-600 text-base py-10'>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
         <div>
         <h3 className='text-3xl font-semibold mt-5'>1. General Collection</h3>
         <p className='text-gray-600 text-base py-4'> <span className='text-black text-xl'>a.</span> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions of electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
         <p className='text-gray-600 text-base py-1'><span className='text-black text-xl'>b.</span> We collect and store information provided by you when you register on our website or use our services.</p>
         <p className='text-gray-600 text-base py-1'><span className='text-black text-xl'>c.</span> We may also collect information automatically through cookies and similar technologies.</p>
         <p className='text-gray-600 text-base py-1'><span className='text-black text-xl'>d.</span> Information collected includes your name, email address, phone number, and other details relevant to the services you use.</p>
         </div>
         <div>
         <h3 className='text-3xl font-semibold mt-5'>2. Collection Of Personal AndOther Information</h3>
         <p className='text-gray-600 text-base py-4'><span className='text-black text-xl'>a.</span>To provide its customers a personalized browsing experience, CountryRoof may collect personal information from you. Additionally, the website may require you to complete a registration form or seek some information from you.</p>
         <p className='text-gray-600 text-base py-1'><span className='text-black text-xl'>b.</span> The User is aware that the Company/Website may automatically track certain information about the User based upon the User's IP address and the User’s behavior on the Website and the User expressly consents to the same. The User is aware that this information is used to do internal research on user demographics, interests, and behavior, which enables the Company/Website to understand better and cater to the interests of its users.</p>

       </div>
         <div>
  <h3 className='text-3xl font-semibold mt-5'>3. COOKIES</h3>
  <p className='text-gray-600 text-base py-4'><span className='text-black text-xl'>a. </span>CountryRoof uses cookies to enhance your browsing experience and provide personalized content. Cookies are small text files stored on your device by our website. You can manage your cookie preferences through your browser settings.</p>
  <p className='text-gray-600 text-base py-1'><span className='text-black text-xl'></span>By continuing to use our website, you consent to the use of cookies in accordance with this Privacy Policy.</p>
  <p className='text-gray-600 text-base py-1'><span className='text-black text-xl'></span>For more information about cookies, please visit our Cookie Policy.</p>
  <p className='text-gray-600 text-base py-1'><span className='text-black text-xl'></span>You may disable cookies through your browser settings, but doing so may affect the functionality of our website.</p>
</div>

         </div>
   </section>
  )
}

export default Privacy
